#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BindingTalk.Droid.Resource", IsApplication=true)]

namespace BindingTalk.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public const int MvxBind = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int MvxDropDownItemTemplate = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int MvxItemTemplate = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public const int MvxLang = 2130771983;
			
			// aapt resource value: 0x7f010013
			public const int MvxSource = 2130771987;
			
			// aapt resource value: 0x7f010010
			public const int MvxTemplate = 2130771984;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int uiCompass = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int uiRotateGestures = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int uiScrollGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiTiltGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiZoomControls = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomGestures = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int useViewLifecycle = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int zOrderOnTop = 2130771981;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040009
			public const int common_action_bar_splitter = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int common_signin_btn_dark_text_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_signin_btn_dark_text_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_signin_btn_dark_text_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_signin_btn_dark_text_pressed = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int common_signin_btn_default_background = 2130968584;
			
			// aapt resource value: 0x7f040004
			public const int common_signin_btn_light_text_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_signin_btn_light_text_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_signin_btn_light_text_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_signin_btn_light_text_pressed = 2130968581;
			
			// aapt resource value: 0x7f04000a
			public const int common_signin_btn_text_dark = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_signin_btn_text_light = 2130968587;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_signin_btn_icon_dark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_signin_btn_icon_disabled_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_focus_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_focus_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_focus_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_normal_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_normal_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_pressed_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_pressed_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_text_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_text_disabled_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_disabled_focus_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_focus_light = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_normal_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_normal_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_pressed_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_pressed_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ndc = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int splash = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int star_gold45 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int star_gold_selector = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int star_grey45 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int star_grey_selector = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public const int FirstNameEdit = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int FullNameLabel = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int MvxBindingTagUnique = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int MyButton = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int SecondNameEdit = 2131034119;
			
			// aapt resource value: 0x7f05000c
			public const int goButton = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int hybrid = 2131034116;
			
			// aapt resource value: 0x7f05000a
			public const int map = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int myTextView = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int normal = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int satellite = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int starbutton = 2131034126;
			
			// aapt resource value: 0x7f050003
			public const int terrain = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int timeTakenText = 2131034125;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AnimatedView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConvertersView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int CustomControlView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FavoritesView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FirstPrinciplesView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FirstView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int FourthPrinciplesView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int FullCommandView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Language2View = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LanguageView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int ListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Main = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MappingView = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MultiView = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int NormalView = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PathView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int QuestionView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int Speed1 = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Speed2 = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Speed3 = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Speed4 = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Speed5 = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int Speed6 = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Speed7 = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int SplashScreen = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int ThinningView = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int ThirdPrinciplesView = 2130903066;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060016
			public const int ApplicationName = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int Hello = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int auth_client_needs_enabling_title = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int auth_client_needs_installation_title = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int auth_client_needs_update_title = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int auth_client_play_services_err_notification_msg = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int auth_client_requested_by_msg = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int auth_client_using_bad_version_title = 2131099663;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_button = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_text = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_enable_title = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_button = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_text_phone = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_tablet = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_install_title = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_unknown_issue = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_unsupported_text = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_unsupported_title = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_update_button = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_text = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_update_title = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int common_signin_button_text = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_signin_button_text_long = 2131099662;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 6
			public const int MapAttrs_uiCompass = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_uiRotateGestures = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_uiScrollGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiTiltGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiZoomControls = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomGestures = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_useViewLifecycle = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_zOrderOnTop = 13;
			
			public static int[] MvxBinding = new int[] {
					2130771982,
					2130771983};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771984};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771987};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771985,
					2130771986};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
